name: trigger this workflow manually 

on:
  workflow_dispatch:

jobs:
  Build_job:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          java_version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: build using maven
        run: mvn clean install

      